### ISSUE TITLE
I need to a Lighttpd for 3.10 linux kernel

### ISSUE THREAD

**Issue by pindonga1234** [alienwithin/OWASP-mth3l3m3nt-framework#2]
Hello to everybody. I hope somebody can help me because I cant buy a new device, it is long to explain but the thing is that I need to lighttpd and php5-cgi for 3.10 linux kernel. I was looking for the first version of lighttpd but I didnt find anything.

**Comment by alienwithin** [comment]
Hi sorry your question isn't quite clear. You want to install it on lighttpd with php5-cgi? have you had a look at [this](https://github.com/alienwithin/OWASP-mth3l3m3nt-framework/wiki/Installation-Linux-(Lighttpd))
